// ─────────────────────────────────────────────────────────────────────────────
// VedMoulya — Mission: USER-SCOPED provider credentials (PROVIDER-01 → Mission)
//
// The contradiction this locks down: a provider the user connected (stored,
// verified credential) was CONNECTED+ACTIVE in the Providers UI while Mission
// honestly reported WAITING_FOR_PROVIDER — because Mission only ever saw
// adapters registered from the DEPLOYMENT environment.
//
// These tests prove the narrow user-scoped seam:
//   - availability is evaluated against the OWNER's orchestrator;
//   - one user's adapter is never visible to another user;
//   - the platform orchestrator still serves availability when no user scope
//     is supplied (existing behavior preserved);
//   - the required-capability predicate is unchanged;
//   - execution uses the OWNER's agent/orchestrator, so generation really runs
//     on the adapter built from the user's own credential.
// ─────────────────────────────────────────────────────────────────────────────

import { describe, it, expect, vi } from 'vitest';
import { AIOrchestrationService } from '@vedmoulya/services';
import type { ProviderAdapter } from '@vedmoulya/services';
import type { AIResponse, CapabilityType, ProviderHealth } from '@vedmoulya/ai';
import type {
  AgentExecutionRun,
  AgentExecutionService,
  AgentPlan,
} from '@vedmoulya/agent-execution';
import { OrchestratorProviderAvailability } from '../adapters/OrchestratorProviderAvailability.js';
import { AgentExecutionAdapter, RunRegistry } from '../adapters/PlanningExecutionPorts.js';
import { createOrchestratorRoutingPorts } from '../adapters/OrchestratorRoutingPorts.js';

// ── Test doubles ────────────────────────────────────────────────────────────

/** A real ProviderAdapter that records what actually executed. */
function recordingProvider(
  name: string,
  capabilities: CapabilityType[],
  log: string[],
): ProviderAdapter {
  return {
    name,
    family: 'google',
    capabilities,
    isHealthy: async () => true,
    getHealth: async (): Promise<ProviderHealth> => ({
      providerId: name,
      status: 'healthy',
      latency: 0,
      errorRate: 0,
      lastChecked: new Date(),
      isRateLimited: false,
      rateLimitRemaining: 0,
      rateLimitReset: null,
    }),
    execute: async (request): Promise<AIResponse> => {
      log.push(`${name}:${request.messages[request.messages.length - 1]?.content ?? ''}`);
      return {
        content: `generated by ${name}`,
        provider: name,
        model: 'user-model',
        confidence: 1,
        qualityScore: 10,
        latency: 1,
        cost: 0,
        tokenUsage: { input: 1, output: 1, total: 2 },
        validation: {
          passed: true,
          checks: [{ name: 'format', passed: true, score: 10 }],
          overallScore: 10,
          decision: 'pass',
        },
        traceId: `${name}-trace`,
        metadata: {
          providerFamily: 'google',
          modelVersion: 'user-model',
          processingTime: 1,
          contextUsed: [],
          routingDecision: {
            selectedProvider: name,
            reason: 'test',
            alternativesConsidered: [],
            strategy: 'balanced',
          },
          validationDetails: [],
        },
      };
    },
  };
}

/** Per-user orchestrator resolver mirroring the production composition. */
function userResolver(
  register: (orchestrator: AIOrchestrationService, userId: string) => Promise<void>,
): (userId: string) => Promise<AIOrchestrationService> {
  const cache = new Map<string, Promise<AIOrchestrationService>>();
  return (userId: string): Promise<AIOrchestrationService> => {
    const existing = cache.get(userId);
    if (existing) return existing;
    const created = (async (): Promise<AIOrchestrationService> => {
      const orchestrator = new AIOrchestrationService();
      await register(orchestrator, userId);
      orchestrator.configureIntelligence(createOrchestratorRoutingPorts(orchestrator));
      return orchestrator;
    })();
    cache.set(userId, created);
    return created;
  };
}

const CODING: CapabilityType[] = ['coding'];

describe('OrchestratorProviderAvailability — user-scoped credentials', () => {
  it('makes a user-connected provider eligible for THAT user only', async () => {
    const resolve = userResolver(async (orchestrator, userId) => {
      if (userId === 'user-a')
        orchestrator.registerProvider(recordingProvider('gemini-user-a', CODING, []));
    });
    const availability = new OrchestratorProviderAvailability(
      new AIOrchestrationService(),
      resolve,
    );

    const forA = await availability.getProviderStatus([], 'user-a');
    const forB = await availability.getProviderStatus([], 'user-b');

    // requiredCapabilities = [] → the vacuous predicate admits a healthy,
    // executable provider (the capability rule itself is unchanged).
    expect(forA.available).toBe(true);
    expect(forA.capableProviders.map((p) => p.providerId)).toEqual(['gemini-user-a']);
    // ...and NEVER another user's provider.
    expect(forB.available).toBe(false);
    expect(forB.capableProviders).toEqual([]);
  });

  it('still evaluates the required-capability predicate (unchanged semantics)', async () => {
    const resolve = userResolver(async (orchestrator) => {
      orchestrator.registerProvider(recordingProvider('coding-only', CODING, []));
    });
    const availability = new OrchestratorProviderAvailability(
      new AIOrchestrationService(),
      resolve,
    );

    expect((await availability.getProviderStatus(['coding'], 'user-a')).available).toBe(true);
    // A capability the adapter does not declare keeps it ineligible.
    expect((await availability.getProviderStatus(['vision'], 'user-a')).available).toBe(false);
  });

  it('preserves platform providers when no user scope is supplied', async () => {
    const platform = new AIOrchestrationService();
    platform.registerProvider(recordingProvider('platform-gemini', CODING, []));
    const availability = new OrchestratorProviderAvailability(platform);

    const status = await availability.getProviderStatus([]);
    expect(status.available).toBe(true);
    expect(status.capableProviders.map((p) => p.providerId)).toEqual(['platform-gemini']);
  });
});

describe('AgentExecutionAdapter — user-scoped execution', () => {
  const plan = { planId: 'plan-1', objective: 'do the work', steps: [] } as unknown as AgentPlan;

  function fakeRun(runId: string): AgentExecutionRun {
    return {
      runId,
      state: 'COMPLETED',
      stepResults: [{ stepId: 's1', status: 'completed', verified: true, attempts: 1 }],
      approvalDecisions: [],
      outcomeReasons: [],
      usage: { tokensUsed: 1, costUsd: 0, latencyMs: 1, toolCalls: 0 },
    } as unknown as AgentExecutionRun;
  }

  it('executes on the OWNER agent resolved from the userId', async () => {
    const defaultStart = vi.fn();
    const userStart = vi.fn(async () => fakeRun('user-run'));
    const defaultAgent = { start: defaultStart } as unknown as AgentExecutionService;
    const resolveUserAgent = vi.fn(
      async () => ({ start: userStart }) as unknown as AgentExecutionService,
    );

    const adapter = new AgentExecutionAdapter(defaultAgent, new RunRegistry(), resolveUserAgent);
    const result = await adapter.executePlan(plan, 'user-a');

    expect(resolveUserAgent).toHaveBeenCalledWith('user-a');
    expect(userStart).toHaveBeenCalledTimes(1);
    expect(defaultStart).not.toHaveBeenCalled();
    expect(result.runId).toBe('user-run');
    expect(result.success).toBe(true);
  });

  it('falls back to the shared agent when no user resolver is wired', async () => {
    const defaultStart = vi.fn(async () => fakeRun('shared-run'));
    const adapter = new AgentExecutionAdapter(
      { start: defaultStart } as unknown as AgentExecutionService,
      new RunRegistry(),
    );

    const result = await adapter.executePlan(plan, 'user-a');
    expect(defaultStart).toHaveBeenCalledTimes(1);
    expect(result.runId).toBe('shared-run');
  });
});

describe('per-user generation — the user credential really reaches the adapter', () => {
  it('routes orchestrate() to the OWNER adapter and never to another user', async () => {
    const executed: string[] = [];
    const resolve = userResolver(async (orchestrator, userId) => {
      if (userId === 'user-a') {
        orchestrator.registerProvider(recordingProvider('openrouter-user-a', CODING, executed));
      }
    });

    const userOrchestrator = await resolve('user-a');
    const response = await userOrchestrator.orchestrate({
      capability: 'coding',
      requiredCapabilities: ['coding'],
      userInput: 'write code',
      userId: 'user-a',
      qualityTier: 'standard',
    });

    expect(response.content).toBe('generated by openrouter-user-a');
    expect(executed).toHaveLength(1);

    // user-b has no adapter for that capability → the runtime refuses honestly.
    const otherOrchestrator = await resolve('user-b');
    await expect(
      otherOrchestrator.orchestrate({
        capability: 'coding',
        requiredCapabilities: ['coding'],
        userInput: 'write code',
        userId: 'user-b',
        qualityTier: 'standard',
      }),
    ).rejects.toThrow();
    expect(executed).toHaveLength(1);
  });
});
