// ──────────────────────────────────────────────────────────────────
// VedMoulya — Learning Intelligence: Seed Catalog
// EI-007 — Enterprise Learning Intelligence Platform
// Realistic seed learning history so the platform demonstrates value
// immediately: provider, context, capability, prompt, budget, quality,
// execution, business, user-preference, and failure signals — all
// referencing the same seed entities the other EI catalogs seed
// (goal_blog_seed, openai, anthropic, research, ctx_*, …). Used for
// dev, the web explorer/dashboard, and tests.
// ──────────────────────────────────────────────────────────────────

import type { LearningCategory, LearningEvent, LearningOutcome } from '../types/learning-types.js';
import { generateLearningEventId } from '../domain/value-objects/LearningEventId.js';

export const SEED_LEARNING_SIZE = 54;

interface SeedEventSpec {
  category: LearningCategory;
  entityType: string;
  entityId: string;
  entityLabel: string;
  outcome: LearningOutcome;
  confidence: number;
  costUsd: number;
  latencyMs: number;
  accuracy: number;
  retries: number;
  quality: number;
  feedback?: number;
  businessOutcome?: number;
  sourceType?: 'goal' | 'task' | 'session' | 'pipeline' | 'manual';
  sourceId?: string;
  daysAgo: number;
  hour: number;
}

function isoDaysAgo(daysAgo: number, hour: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hour, 15, 0, 0);
  return date.toISOString();
}

function event(spec: SeedEventSpec): LearningEvent {
  return {
    eventId: generateLearningEventId(),
    category: spec.category,
    entityType: spec.entityType,
    entityId: spec.entityId,
    entityLabel: spec.entityLabel,
    outcome: spec.outcome,
    confidence: spec.confidence,
    costUsd: spec.costUsd,
    latencyMs: spec.latencyMs,
    accuracy: spec.accuracy,
    retries: spec.retries,
    quality: spec.quality,
    feedback: spec.feedback,
    businessOutcome: spec.businessOutcome,
    sourceRef:
      spec.sourceType && spec.sourceId
        ? { sourceType: spec.sourceType, sourceId: spec.sourceId }
        : undefined,
    metadata: { seed: true },
    occurredAt: isoDaysAgo(spec.daysAgo, spec.hour),
    createdAt: isoDaysAgo(spec.daysAgo, spec.hour),
  };
}

/** Build the seed learning catalog (38 events across all 10 categories). */
export function createCatalogLearningEvents(): LearningEvent[] {
  return [
    // ── Provider learning ─────────────────────────────────────────────────
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'openai',
      entityLabel: 'OpenAI',
      outcome: 'success',
      confidence: 0.95,
      costUsd: 0.008,
      latencyMs: 420,
      accuracy: 0.96,
      retries: 0,
      quality: 0.94,
      feedback: 0.9,
      businessOutcome: 0.8,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 13,
      hour: 9,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'openai',
      entityLabel: 'OpenAI',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.007,
      latencyMs: 380,
      accuracy: 0.95,
      retries: 0,
      quality: 0.93,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 11,
      hour: 10,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'openai',
      entityLabel: 'OpenAI',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.009,
      latencyMs: 450,
      accuracy: 0.94,
      retries: 1,
      quality: 0.91,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 8,
      hour: 11,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'openai',
      entityLabel: 'OpenAI',
      outcome: 'success',
      confidence: 0.93,
      costUsd: 0.006,
      latencyMs: 360,
      accuracy: 0.97,
      retries: 0,
      quality: 0.95,
      feedback: 0.95,
      sourceType: 'session',
      sourceId: 'sess_blog_04',
      daysAgo: 4,
      hour: 12,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'openai',
      entityLabel: 'OpenAI',
      outcome: 'success',
      confidence: 0.94,
      costUsd: 0.008,
      latencyMs: 410,
      accuracy: 0.95,
      retries: 0,
      quality: 0.94,
      feedback: 0.9,
      businessOutcome: 0.85,
      sourceType: 'session',
      sourceId: 'sess_blog_05',
      daysAgo: 1,
      hour: 13,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'anthropic',
      entityLabel: 'Anthropic',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.014,
      latencyMs: 620,
      accuracy: 0.93,
      retries: 0,
      quality: 0.92,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 12,
      hour: 9,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'anthropic',
      entityLabel: 'Anthropic',
      outcome: 'failure',
      confidence: 0.85,
      costUsd: 0.012,
      latencyMs: 1800,
      accuracy: 0.6,
      retries: 3,
      quality: 0.4,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 9,
      hour: 10,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'anthropic',
      entityLabel: 'Anthropic',
      outcome: 'success',
      confidence: 0.91,
      costUsd: 0.013,
      latencyMs: 640,
      accuracy: 0.94,
      retries: 0,
      quality: 0.93,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 5,
      hour: 11,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'google',
      entityLabel: 'Google',
      outcome: 'failure',
      confidence: 0.8,
      costUsd: 0.004,
      latencyMs: 2400,
      accuracy: 0.5,
      retries: 4,
      quality: 0.35,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 10,
      hour: 14,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'google',
      entityLabel: 'Google',
      outcome: 'failure',
      confidence: 0.82,
      costUsd: 0.005,
      latencyMs: 2100,
      accuracy: 0.55,
      retries: 3,
      quality: 0.4,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 6,
      hour: 15,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'deepseek',
      entityLabel: 'DeepSeek',
      outcome: 'success',
      confidence: 0.88,
      costUsd: 0.002,
      latencyMs: 900,
      accuracy: 0.88,
      retries: 0,
      quality: 0.82,
      sourceType: 'task',
      sourceId: 'task_summary_01',
      daysAgo: 7,
      hour: 9,
    }),
    event({
      category: 'provider',
      entityType: 'provider',
      entityId: 'deepseek',
      entityLabel: 'DeepSeek',
      outcome: 'success',
      confidence: 0.87,
      costUsd: 0.0015,
      latencyMs: 850,
      accuracy: 0.87,
      retries: 1,
      quality: 0.8,
      feedback: 0.7,
      sourceType: 'task',
      sourceId: 'task_summary_02',
      daysAgo: 2,
      hour: 10,
    }),

    // ── Context learning ──────────────────────────────────────────────────
    event({
      category: 'context',
      entityType: 'context',
      entityId: 'ctx_knowledge_provider_001',
      entityLabel: 'Provider knowledge base',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.001,
      latencyMs: 120,
      accuracy: 0.95,
      retries: 0,
      quality: 0.93,
      feedback: 0.9,
      sourceType: 'pipeline',
      sourceId: 'pipeline_blog_01',
      daysAgo: 12,
      hour: 9,
    }),
    event({
      category: 'context',
      entityType: 'context',
      entityId: 'ctx_knowledge_provider_001',
      entityLabel: 'Provider knowledge base',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.001,
      latencyMs: 110,
      accuracy: 0.96,
      retries: 0,
      quality: 0.94,
      sourceType: 'pipeline',
      sourceId: 'pipeline_blog_02',
      daysAgo: 5,
      hour: 10,
    }),
    event({
      category: 'context',
      entityType: 'context',
      entityId: 'ctx_knowledge_arch_001',
      entityLabel: 'Architecture knowledge',
      outcome: 'failure',
      confidence: 0.75,
      costUsd: 0.002,
      latencyMs: 900,
      accuracy: 0.55,
      retries: 2,
      quality: 0.45,
      sourceType: 'pipeline',
      sourceId: 'pipeline_blog_01',
      daysAgo: 11,
      hour: 13,
    }),
    event({
      category: 'context',
      entityType: 'context',
      entityId: 'ctx_user_profile_001',
      entityLabel: 'User profile context',
      outcome: 'success',
      confidence: 0.88,
      costUsd: 0.0005,
      latencyMs: 90,
      accuracy: 0.93,
      retries: 0,
      quality: 0.9,
      feedback: 0.85,
      sourceType: 'session',
      sourceId: 'sess_blog_04',
      daysAgo: 3,
      hour: 12,
    }),
    event({
      category: 'context',
      entityType: 'context',
      entityId: 'ctx_knowledge_provider_001',
      entityLabel: 'Provider knowledge base',
      outcome: 'success',
      confidence: 0.91,
      costUsd: 0.0008,
      latencyMs: 100,
      accuracy: 0.95,
      retries: 0,
      quality: 0.93,
      feedback: 0.9,
      sourceType: 'pipeline',
      sourceId: 'pipeline_blog_03',
      daysAgo: 1,
      hour: 10,
    }),

    // ── Capability learning ───────────────────────────────────────────────
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'research',
      entityLabel: 'Research',
      outcome: 'success',
      confidence: 0.93,
      costUsd: 0.004,
      latencyMs: 800,
      accuracy: 0.95,
      retries: 0,
      quality: 0.94,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 13,
      hour: 9,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'research',
      entityLabel: 'Research',
      outcome: 'success',
      confidence: 0.91,
      costUsd: 0.0035,
      latencyMs: 750,
      accuracy: 0.94,
      retries: 0,
      quality: 0.93,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 6,
      hour: 10,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'writing',
      entityLabel: 'Writing',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.005,
      latencyMs: 700,
      accuracy: 0.94,
      retries: 0,
      quality: 0.93,
      feedback: 0.88,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 10,
      hour: 11,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'content_generation',
      entityLabel: 'Content Generation',
      outcome: 'failure',
      confidence: 0.8,
      costUsd: 0.02,
      latencyMs: 3000,
      accuracy: 0.5,
      retries: 3,
      quality: 0.4,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 9,
      hour: 14,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'content_generation',
      entityLabel: 'Content Generation',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.011,
      latencyMs: 1500,
      accuracy: 0.92,
      retries: 1,
      quality: 0.88,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 4,
      hour: 11,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'seo_optimization',
      entityLabel: 'SEO Optimization',
      outcome: 'success',
      confidence: 0.87,
      costUsd: 0.002,
      latencyMs: 500,
      accuracy: 0.9,
      retries: 0,
      quality: 0.86,
      businessOutcome: 0.75,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 2,
      hour: 12,
    }),
    event({
      category: 'capability',
      entityType: 'capability',
      entityId: 'research',
      entityLabel: 'Research',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.004,
      latencyMs: 780,
      accuracy: 0.95,
      retries: 0,
      quality: 0.94,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 1,
      hour: 9,
    }),

    // ── Prompt learning ───────────────────────────────────────────────────
    event({
      category: 'prompt',
      entityType: 'prompt',
      entityId: 'prompt_blog_v1',
      entityLabel: 'Blog template v1',
      outcome: 'success',
      confidence: 0.85,
      costUsd: 0.006,
      latencyMs: 600,
      accuracy: 0.86,
      retries: 0,
      quality: 0.8,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 13,
      hour: 10,
    }),
    event({
      category: 'prompt',
      entityType: 'prompt',
      entityId: 'prompt_blog_v1',
      entityLabel: 'Blog template v1',
      outcome: 'failure',
      confidence: 0.8,
      costUsd: 0.007,
      latencyMs: 1500,
      accuracy: 0.5,
      retries: 2,
      quality: 0.42,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 9,
      hour: 11,
    }),
    event({
      category: 'prompt',
      entityType: 'prompt',
      entityId: 'prompt_blog_v2',
      entityLabel: 'Blog template v2',
      outcome: 'success',
      confidence: 0.94,
      costUsd: 0.006,
      latencyMs: 520,
      accuracy: 0.96,
      retries: 0,
      quality: 0.95,
      feedback: 0.92,
      sourceType: 'session',
      sourceId: 'sess_blog_04',
      daysAgo: 5,
      hour: 12,
    }),
    event({
      category: 'prompt',
      entityType: 'prompt',
      entityId: 'prompt_blog_v2',
      entityLabel: 'Blog template v2',
      outcome: 'success',
      confidence: 0.95,
      costUsd: 0.005,
      latencyMs: 480,
      accuracy: 0.97,
      retries: 0,
      quality: 0.96,
      feedback: 0.95,
      businessOutcome: 0.85,
      sourceType: 'session',
      sourceId: 'sess_blog_05',
      daysAgo: 1,
      hour: 13,
    }),
    event({
      category: 'prompt',
      entityType: 'prompt',
      entityId: 'prompt_blog_v2',
      entityLabel: 'Blog template v2',
      outcome: 'success',
      confidence: 0.93,
      costUsd: 0.0055,
      latencyMs: 510,
      accuracy: 0.95,
      retries: 0,
      quality: 0.94,
      feedback: 0.9,
      sourceType: 'session',
      sourceId: 'sess_blog_06',
      daysAgo: 0,
      hour: 11,
    }),

    // ── Budget learning ───────────────────────────────────────────────────
    event({
      category: 'budget',
      entityType: 'budget',
      entityId: 'budget_standard',
      entityLabel: 'Standard budget ($1.00/run)',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.6,
      latencyMs: 600,
      accuracy: 0.93,
      retries: 0,
      quality: 0.91,
      sourceType: 'pipeline',
      sourceId: 'strat_blog_001',
      daysAgo: 12,
      hour: 9,
    }),
    event({
      category: 'budget',
      entityType: 'budget',
      entityId: 'budget_standard',
      entityLabel: 'Standard budget ($1.00/run)',
      outcome: 'success',
      confidence: 0.91,
      costUsd: 0.55,
      latencyMs: 580,
      accuracy: 0.94,
      retries: 0,
      quality: 0.92,
      sourceType: 'pipeline',
      sourceId: 'strat_blog_001',
      daysAgo: 7,
      hour: 10,
    }),
    event({
      category: 'budget',
      entityType: 'budget',
      entityId: 'budget_premium',
      entityLabel: 'Premium budget ($3.00/run)',
      outcome: 'failure',
      confidence: 0.86,
      costUsd: 2.4,
      latencyMs: 2200,
      accuracy: 0.6,
      retries: 2,
      quality: 0.5,
      sourceType: 'pipeline',
      sourceId: 'strat_premium_001',
      daysAgo: 8,
      hour: 13,
    }),
    event({
      category: 'budget',
      entityType: 'budget',
      entityId: 'budget_standard',
      entityLabel: 'Standard budget ($1.00/run)',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.5,
      latencyMs: 560,
      accuracy: 0.95,
      retries: 0,
      quality: 0.93,
      sourceType: 'pipeline',
      sourceId: 'strat_blog_001',
      daysAgo: 0,
      hour: 9,
    }),

    // ── Quality learning ──────────────────────────────────────────────────
    event({
      category: 'quality',
      entityType: 'quality_target',
      entityId: 'quality_premium',
      entityLabel: 'Premium quality target',
      outcome: 'success',
      confidence: 0.93,
      costUsd: 0.012,
      latencyMs: 900,
      accuracy: 0.95,
      retries: 0,
      quality: 0.95,
      feedback: 0.9,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 10,
      hour: 11,
    }),
    event({
      category: 'quality',
      entityType: 'quality_target',
      entityId: 'quality_standard',
      entityLabel: 'Standard quality target',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.006,
      latencyMs: 500,
      accuracy: 0.92,
      retries: 0,
      quality: 0.87,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 6,
      hour: 12,
    }),
    event({
      category: 'quality',
      entityType: 'quality_target',
      entityId: 'quality_standard',
      entityLabel: 'Standard quality target',
      outcome: 'failure',
      confidence: 0.85,
      costUsd: 0.008,
      latencyMs: 1600,
      accuracy: 0.5,
      retries: 3,
      quality: 0.38,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 3,
      hour: 14,
    }),

    // ── Execution learning ────────────────────────────────────────────────
    event({
      category: 'execution',
      entityType: 'strategy',
      entityId: 'strat_blog_001',
      entityLabel: 'Blog pipeline strategy',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.02,
      latencyMs: 5000,
      accuracy: 0.94,
      retries: 0,
      quality: 0.93,
      sourceType: 'session',
      sourceId: 'sess_blog_04',
      daysAgo: 11,
      hour: 10,
    }),
    event({
      category: 'execution',
      entityType: 'strategy',
      entityId: 'strat_blog_001',
      entityLabel: 'Blog pipeline strategy',
      outcome: 'success',
      confidence: 0.91,
      costUsd: 0.018,
      latencyMs: 4800,
      accuracy: 0.93,
      retries: 0,
      quality: 0.92,
      sourceType: 'session',
      sourceId: 'sess_blog_05',
      daysAgo: 4,
      hour: 10,
    }),
    event({
      category: 'execution',
      entityType: 'strategy',
      entityId: 'strat_blog_001',
      entityLabel: 'Blog pipeline strategy',
      outcome: 'success',
      confidence: 0.93,
      costUsd: 0.019,
      latencyMs: 4900,
      accuracy: 0.95,
      retries: 0,
      quality: 0.94,
      feedback: 0.92,
      sourceType: 'session',
      sourceId: 'sess_blog_06',
      daysAgo: 0,
      hour: 10,
    }),
    event({
      category: 'execution',
      entityType: 'execution_pattern',
      entityId: 'sequential',
      entityLabel: 'Sequential execution',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.015,
      latencyMs: 6000,
      accuracy: 0.93,
      retries: 0,
      quality: 0.92,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 9,
      hour: 11,
    }),
    event({
      category: 'execution',
      entityType: 'execution_pattern',
      entityId: 'parallel',
      entityLabel: 'Parallel execution',
      outcome: 'failure',
      confidence: 0.84,
      costUsd: 0.03,
      latencyMs: 2500,
      accuracy: 0.55,
      retries: 3,
      quality: 0.4,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 7,
      hour: 13,
    }),
    event({
      category: 'execution',
      entityType: 'execution_pattern',
      entityId: 'hybrid',
      entityLabel: 'Hybrid execution',
      outcome: 'success',
      confidence: 0.88,
      costUsd: 0.02,
      latencyMs: 4000,
      accuracy: 0.9,
      retries: 1,
      quality: 0.87,
      sourceType: 'session',
      sourceId: 'sess_blog_05',
      daysAgo: 2,
      hour: 12,
    }),
    event({
      category: 'execution',
      entityType: 'execution_pattern',
      entityId: 'hybrid',
      entityLabel: 'Hybrid execution',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.019,
      latencyMs: 3800,
      accuracy: 0.92,
      retries: 0,
      quality: 0.9,
      sourceType: 'session',
      sourceId: 'sess_blog_06',
      daysAgo: 1,
      hour: 11,
    }),
    event({
      category: 'execution',
      entityType: 'execution_pattern',
      entityId: 'hybrid',
      entityLabel: 'Hybrid execution',
      outcome: 'failure',
      confidence: 0.82,
      costUsd: 0.022,
      latencyMs: 4200,
      accuracy: 0.6,
      retries: 2,
      quality: 0.5,
      sourceType: 'session',
      sourceId: 'sess_blog_07',
      daysAgo: 0,
      hour: 15,
    }),

    // ── Business learning ─────────────────────────────────────────────────
    event({
      category: 'business',
      entityType: 'client',
      entityId: 'client_acme',
      entityLabel: 'Acme client',
      outcome: 'success',
      confidence: 0.9,
      costUsd: 0.4,
      latencyMs: 300,
      accuracy: 0.9,
      retries: 0,
      quality: 0.85,
      feedback: 0.9,
      businessOutcome: 0.95,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 8,
      hour: 9,
    }),
    event({
      category: 'business',
      entityType: 'client',
      entityId: 'client_acme',
      entityLabel: 'Acme client',
      outcome: 'success',
      confidence: 0.92,
      costUsd: 0.35,
      latencyMs: 280,
      accuracy: 0.92,
      retries: 0,
      quality: 0.88,
      feedback: 0.92,
      businessOutcome: 0.9,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 1,
      hour: 10,
    }),
    event({
      category: 'business',
      entityType: 'segment',
      entityId: 'segment_enterprise',
      entityLabel: 'Enterprise segment',
      outcome: 'success',
      confidence: 0.87,
      costUsd: 0.5,
      latencyMs: 350,
      accuracy: 0.88,
      retries: 0,
      quality: 0.84,
      businessOutcome: 0.85,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 5,
      hour: 11,
    }),

    // ── User preference learning ──────────────────────────────────────────
    event({
      category: 'user_preference',
      entityType: 'user',
      entityId: 'user_demo',
      entityLabel: 'Demo user',
      outcome: 'success',
      confidence: 0.88,
      costUsd: 0.001,
      latencyMs: 100,
      accuracy: 0.9,
      retries: 0,
      quality: 0.86,
      feedback: 0.9,
      sourceType: 'manual',
      sourceId: 'manual_pref_01',
      daysAgo: 6,
      hour: 10,
    }),
    event({
      category: 'user_preference',
      entityType: 'tone',
      entityId: 'tone_professional',
      entityLabel: 'Professional tone',
      outcome: 'success',
      confidence: 0.86,
      costUsd: 0.002,
      latencyMs: 150,
      accuracy: 0.89,
      retries: 0,
      quality: 0.85,
      feedback: 0.85,
      sourceType: 'manual',
      sourceId: 'manual_pref_02',
      daysAgo: 3,
      hour: 11,
    }),
    event({
      category: 'user_preference',
      entityType: 'tone',
      entityId: 'tone_casual',
      entityLabel: 'Casual tone',
      outcome: 'failure',
      confidence: 0.7,
      costUsd: 0.003,
      latencyMs: 400,
      accuracy: 0.5,
      retries: 2,
      quality: 0.4,
      feedback: 0.3,
      sourceType: 'manual',
      sourceId: 'manual_pref_03',
      daysAgo: 2,
      hour: 13,
    }),

    // ── Failure learning ──────────────────────────────────────────────────
    event({
      category: 'failure',
      entityType: 'provider',
      entityId: 'google',
      entityLabel: 'Google',
      outcome: 'failure',
      confidence: 0.85,
      costUsd: 0.005,
      latencyMs: 2300,
      accuracy: 0.5,
      retries: 4,
      quality: 0.35,
      sourceType: 'session',
      sourceId: 'sess_blog_02',
      daysAgo: 10,
      hour: 14,
    }),
    event({
      category: 'failure',
      entityType: 'provider',
      entityId: 'google',
      entityLabel: 'Google',
      outcome: 'failure',
      confidence: 0.83,
      costUsd: 0.006,
      latencyMs: 2500,
      accuracy: 0.45,
      retries: 4,
      quality: 0.3,
      sourceType: 'session',
      sourceId: 'sess_blog_03',
      daysAgo: 4,
      hour: 15,
    }),
    event({
      category: 'failure',
      entityType: 'capability',
      entityId: 'content_generation',
      entityLabel: 'Content Generation',
      outcome: 'failure',
      confidence: 0.82,
      costUsd: 0.02,
      latencyMs: 2900,
      accuracy: 0.5,
      retries: 3,
      quality: 0.38,
      sourceType: 'goal',
      sourceId: 'goal_blog_seed',
      daysAgo: 9,
      hour: 14,
    }),
    event({
      category: 'failure',
      entityType: 'execution_pattern',
      entityId: 'parallel',
      entityLabel: 'Parallel execution',
      outcome: 'failure',
      confidence: 0.8,
      costUsd: 0.028,
      latencyMs: 2400,
      accuracy: 0.5,
      retries: 3,
      quality: 0.35,
      sourceType: 'session',
      sourceId: 'sess_blog_01',
      daysAgo: 7,
      hour: 13,
    }),
  ];
}
