// ──────────────────────────────────────────────────────────────────
// VedMoulya — AI Application Factory: Deterministic Project Generator
// EPIC-007 — Phases 5/18. Generates typed, structured, testable,
// lintable, buildable project files for the three validation projects
// (ABAP Debugger, Restaurant App, AI App Builder) + the generic web
// fallback. Hermetic and deterministic — no network, no secrets.
//
// The generator is a TEMPLATE ENGINE, not a model: it produces
// coherent source/config/test/schema/docs files that the Validation
// Pipeline gates actually run against. Live external builds (tsc, npm
// install) on a materialized project are a documented operator step.
// ──────────────────────────────────────────────────────────────────

import type { AppArchetype, BlueprintFile } from '../types/app-types.js';

export interface GeneratedFile {
  path: string;
  content: string;
  kind: BlueprintFile['kind'];
}

export interface GenerateOptions {
  applicationId: string;
  name: string;
  /** Inject a defect for the auto-fix benchmark/tests (missing tests). */
  injectDefects?: boolean;
  /** Inject a hard-coded secret to prove the security gate blocks it. */
  injectSecret?: boolean;
}

export function generateProject(
  archetype: AppArchetype,
  options: GenerateOptions,
): GeneratedFile[] {
  switch (archetype) {
    case 'abap-debugger':
      return generateAbap(options);
    case 'restaurant-app':
      return generateRestaurant(options);
    case 'ai-app-builder':
      return generateAiBuilder(options);
    default:
      return generateGeneric(options);
  }
}

function generateAbap(options: GenerateOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [
    file(
      'package.json',
      JSON.stringify(
        {
          name: options.name,
          version: '0.1.0',
          private: true,
          scripts: { build: 'tsc -p tsconfig.json', test: 'vitest run', lint: 'tsc --noEmit' },
          dependencies: { '@vedmoulya/core': '*' },
          devDependencies: { typescript: '^5.6.0', vitest: '^4.1.10' },
        },
        null,
        2,
      ),
      'config',
    ),
    file(
      'tsconfig.json',
      JSON.stringify(
        { compilerOptions: { strict: true, target: 'ES2022', module: 'ESNext' }, include: ['src'] },
        null,
        2,
      ),
      'config',
    ),
    file(
      'src/index.ts',
      [
        'export interface Diagnosis { explanation: string; correctedCode: string; }',
        '',
        'const SYSTEM_KEYWORDS: string[] = ["FIELD-SYMBOLS", "ASSIGN", "REF TO", "DATA("];',
        '',
        'export function analyzeSnippet(code: string, error: string): string {',
        '  const suspicious = SYSTEM_KEYWORDS.filter((k) => code.includes(k));',
        '  return `Suspicious statements: ${suspicious.join(", ") || "none detected"} — error: ${error}`;',
        '}',
        '',
        'export function suggestCorrection(code: string): string {',
        '  if (code.includes("ASSIGN") && !code.includes("IS ASSIGNED")) {',
        '    return code.replace("ASSIGN", "IF <fs> IS ASSIGNED.\\nASSIGN");',
        '  }',
        '  return code;',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/index.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { analyzeSnippet, suggestCorrection } from "./index.js";',
        '',
        'describe("ABAP debugger", () => {',
        '  it("analyzes a snippet", () => {',
        '    expect(analyzeSnippet("ASSIGN lv_ref", "short dump")).toContain("ASSIGN");',
        '  });',
        '  it("suggests a correction for unguarded ASSIGN", () => {',
        '    expect(suggestCorrection("ASSIGN lv_ref")).toContain("IS ASSIGNED");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui/app.ts',
      [
        '// Deterministic UI entry — bundled by the gateway preview sandbox (Phase 13).',
        "import { analyzeSnippet, suggestCorrection } from '../index.js';",
        '',
        'export const uiTitle = "ABAP Debugger Assistant";',
        '',
        'export function render(root: HTMLElement): void {',
        '  const style = document.createElement("style");',
        '  style.textContent = [',
        '    ":root { color-scheme: light dark; --bg: #ffffff; --fg: #0f172a; --muted: #64748b; }",',
        '    "@media (prefers-color-scheme: dark) { :root { --bg: #0f172a; --fg: #e2e8f0; --muted: #94a3b8; } }",',
        '    "body { margin: 0; font-family: system-ui, Inter, sans-serif; background: var(--bg); color: var(--fg); }",',
        '    ".shell { max-width: 720px; margin: 0 auto; padding: 24px; display: flex; flex-direction: column; gap: 12px; }",',
        '    "@media (max-width: 768px) { .shell { padding: 16px; } }",',
        '    "textarea, input { width: 100%; box-sizing: border-box; padding: 8px; border: 1px solid #cbd5e1; border-radius: 8px; font: inherit; }",',
        '    "button { padding: 8px 16px; border: 0; border-radius: 8px; background: #2b5fd9; color: #fff; font: inherit; cursor: pointer; }",',
        '    ".banner { border: 1px solid; border-radius: 8px; padding: 10px; font-size: 14px; }",',
        '    ".banner.ok { border-color: #10b981; color: #065f46; }",',
        '    ".banner.err { border-color: #ef4444; color: #991b1b; }",',
        '    ".muted { color: var(--muted); font-size: 12px; }",',
        '    "pre { white-space: pre-wrap; background: rgba(127,127,127,0.08); border-radius: 8px; padding: 10px; font-size: 13px; }"',
        '  ].join("\\n");',
        '  root.appendChild(style);',
        '',
        '  const shell = document.createElement("main");',
        '  shell.className = "shell";',
        '',
        '  const title = document.createElement("h1");',
        '  title.textContent = uiTitle;',
        '',
        '  const codeLabel = document.createElement("label");',
        '  codeLabel.setAttribute("aria-label", "ABAP source code");',
        '  const code = document.createElement("textarea");',
        '  code.rows = 8;',
        '  code.placeholder = "Paste ABAP source, e.g. ASSIGN lv_ref.";',
        '  codeLabel.appendChild(code);',
        '',
        '  const errLabel = document.createElement("label");',
        '  errLabel.setAttribute("aria-label", "Error message");',
        '  const errorInput = document.createElement("input");',
        '  errorInput.placeholder = "Error message, e.g. short dump";',
        '  errLabel.appendChild(errorInput);',
        '',
        '  const analyze = document.createElement("button");',
        '  analyze.type = "button";',
        '  analyze.textContent = "Analyze";',
        '',
        '  const status = document.createElement("p");',
        '  status.className = "muted";',
        '  status.textContent = "Empty — paste a snippet to begin.";',
        '',
        '  const output = document.createElement("section");',
        '  output.setAttribute("aria-live", "polite");',
        '',
        '  analyze.addEventListener("click", () => {',
        '    const snippet = code.value.trim();',
        '    if (!snippet) {',
        '      status.textContent = "Empty — paste ABAP source first.";',
        '      output.replaceChildren();',
        '      return;',
        '    }',
        '    status.textContent = "Loading — analyzing…";',
        '    try {',
        '      const diagnosis = analyzeSnippet(snippet, errorInput.value.trim() || "unknown error");',
        '      const corrected = suggestCorrection(snippet);',
        '      const ok = document.createElement("div");',
        '      ok.className = "banner ok";',
        '      ok.textContent = diagnosis;',
        '      const fix = document.createElement("pre");',
        '      fix.textContent = corrected;',
        '      output.replaceChildren(ok, fix);',
        '      status.textContent = "Done — see the diagnosis above.";',
        '    } catch (err) {',
        '      const fail = document.createElement("div");',
        '      fail.className = "banner err";',
        '      fail.textContent = err instanceof Error ? err.message : "Analysis failed.";',
        '      output.replaceChildren(fail);',
        '      status.textContent = "Error — analysis failed.";',
        '    }',
        '  });',
        '',
        '  shell.append(title, codeLabel, errLabel, analyze, status, output);',
        '  root.appendChild(shell);',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/ui/app.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { uiTitle, render } from "./app.js";',
        '',
        'describe("ABAP UI entry", () => {',
        '  it("exposes a render function and a title", () => {',
        '    expect(typeof render).toBe("function");',
        '    expect(uiTitle).toContain("ABAP");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui-design.md',
      [
        '# UI Design — ABAP Debugger Assistant',
        'Responsive single-page tool: paste ABAP + error, view diagnosis.',
        'Navigation: header nav, back button. Loading state while analyzing.',
        'Empty state: no snippet yet. Error state: parse failure banner.',
        'Accessibility: aria-labels on inputs, keyboard focus, 4.5:1 contrast.',
        'Dark/light mode via CSS variables. Design tokens: spacing 4px scale, Inter typography.',
        'Mobile: stacked layout under 768px. Desktop: two-column diagnosis + code.',
      ].join('\n'),
      'docs',
    ),
    file(
      'db/schema.sql',
      [
        'CREATE TABLE IF NOT EXISTS snippets (',
        '  id UUID PRIMARY KEY,',
        '  code TEXT NOT NULL,',
        '  error_message TEXT,',
        '  created_at TIMESTAMPTZ NOT NULL DEFAULT now()',
        ');',
        'CREATE TABLE IF NOT EXISTS diagnoses (',
        '  id UUID PRIMARY KEY,',
        '  snippet_id UUID REFERENCES snippets(id),',
        '  explanation TEXT NOT NULL,',
        '  corrected_code TEXT NOT NULL',
        ');',
      ].join('\n'),
      'schema',
    ),
  ];
  return applyDefects(files, options);
}

function generateRestaurant(options: GenerateOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [
    file(
      'package.json',
      JSON.stringify(
        {
          name: options.name,
          version: '0.1.0',
          private: true,
          scripts: { build: 'tsc -p tsconfig.json', test: 'vitest run', lint: 'tsc --noEmit' },
          dependencies: { next: '^15.0.0', react: '^19.0.0', '@vedmoulya/core': '*' },
          devDependencies: { typescript: '^5.6.0', vitest: '^4.1.10' },
        },
        null,
        2,
      ),
      'config',
    ),
    file(
      'tsconfig.json',
      JSON.stringify(
        { compilerOptions: { strict: true, jsx: 'react-jsx', target: 'ES2022' }, include: ['src'] },
        null,
        2,
      ),
      'config',
    ),
    file(
      'src/index.ts',
      [
        'export { groupByCategory } from "./api/menu.js";',
        'export { addToCart, cartTotal } from "./api/cart.js";',
        'export { placeOrder } from "./api/orders.js";',
        '',
        'export type { MenuItem, Category } from "./api/menu.js";',
        'export type { CartLine } from "./api/cart.js";',
        'export type { Order } from "./api/orders.js";',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/index.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { groupByCategory, addToCart } from "./index.js";',
        '',
        'describe("restaurant entry", () => {',
        '  it("re-exports the API modules", () => {',
        '    expect(typeof groupByCategory).toBe("function");',
        '    expect(typeof addToCart).toBe("function");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/api/menu.ts',
      [
        'export interface MenuItem { id: string; name: string; price: number; categoryId: string; available: boolean; }',
        'export interface Category { id: string; name: string; sortOrder: number; }',
        '',
        'export function groupByCategory(items: MenuItem[], categories: Category[]): Array<{ category: Category; items: MenuItem[] }> {',
        '  return categories.map((category) => ({',
        '    category,',
        '    items: items.filter((item) => item.categoryId === category.id && item.available),',
        '  }));',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/api/cart.ts',
      [
        'export interface CartLine { itemId: string; quantity: number; }',
        '',
        'export function addToCart(lines: CartLine[], itemId: string, quantity = 1): CartLine[] {',
        '  const existing = lines.find((l) => l.itemId === itemId);',
        '  if (existing) return lines.map((l) => (l.itemId === itemId ? { ...l, quantity: l.quantity + quantity } : l));',
        '  return [...lines, { itemId, quantity }];',
        '}',
        '',
        'export function cartTotal(lines: CartLine[], prices: Record<string, number>): number {',
        '  return lines.reduce((sum, line) => sum + (prices[line.itemId] ?? 0) * line.quantity, 0);',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/api/orders.ts',
      [
        'export interface Order { id: string; userId: string; status: string; total: number; }',
        'export type OrderStatus = "pending" | "confirmed" | "preparing" | "ready" | "completed" | "cancelled";',
        '',
        'export function placeOrder(userId: string, total: number): Order {',
        '  return { id: crypto.randomUUID(), userId, status: "pending", total };',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/api/menu.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { groupByCategory } from "./menu.js";',
        '',
        'describe("menu", () => {',
        '  it("groups menu items by category", () => {',
        '    const groups = groupByCategory(',
        '      [{ id: "1", name: "Pizza", price: 12, categoryId: "main", available: true }],',
        '      [{ id: "main", name: "Mains", sortOrder: 1 }],',
        '    );',
        '    expect(groups[0].items).toHaveLength(1);',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/api/cart.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { addToCart, cartTotal } from "./cart.js";',
        '',
        'describe("cart", () => {',
        '  it("adds to cart and totals", () => {',
        '    const cart = addToCart([], "1");',
        '    expect(cartTotal(cart, { "1": 12 })).toBe(12);',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/api/orders.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { placeOrder } from "./orders.js";',
        '',
        'describe("orders", () => {',
        '  it("places an order", () => {',
        '    const order = placeOrder("u1", 24);',
        '    expect(order.status).toBe("pending");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui/app.ts',
      [
        '// Deterministic UI entry — bundled by the gateway preview sandbox (Phase 13).',
        "import { groupByCategory, addToCart, cartTotal } from '../index.js';",
        '',
        'export const uiTitle = "Restaurant App";',
        '',
        'export function render(root: HTMLElement): void {',
        '  const style = document.createElement("style");',
        '  style.textContent = [',
        '    ":root { color-scheme: light dark; --bg: #ffffff; --fg: #0f172a; --accent: #ea580c; }",',
        '    "@media (prefers-color-scheme: dark) { :root { --bg: #0f172a; --fg: #e2e8f0; } }",',
        '    "body { margin: 0; font-family: system-ui, Inter, sans-serif; background: var(--bg); color: var(--fg); }",',
        '    ".shell { max-width: 720px; margin: 0 auto; padding: 24px; display: flex; flex-direction: column; gap: 12px; }",',
        '    "@media (max-width: 768px) { .shell { padding: 16px; } }",',
        '    "button { padding: 6px 12px; border: 0; border-radius: 8px; background: var(--accent); color: #fff; font: inherit; cursor: pointer; }",',
        '    ".row { display: flex; align-items: center; justify-content: space-between; gap: 8px; border-bottom: 1px solid rgba(127,127,127,0.2); padding: 6px 0; font-size: 14px; }",',
        '    ".muted { color: #64748b; font-size: 12px; }",',
        '  ].join("\\n");',
        '  root.appendChild(style);',
        '',
        '  const shell = document.createElement("main");',
        '  shell.className = "shell";',
        '',
        '  const title = document.createElement("h1");',
        '  title.textContent = uiTitle;',
        '',
        '  const menuItems = [',
        '    { id: "1", name: "Margherita pizza", price: 12, categoryId: "main", available: true },',
        '    { id: "2", name: "Garlic bread", price: 6, categoryId: "starter", available: true },',
        '    { id: "3", name: "Tiramisu", price: 8, categoryId: "dessert", available: false },',
        '  ];',
        '  const categories = [',
        '    { id: "starter", name: "Starters", sortOrder: 1 },',
        '    { id: "main", name: "Mains", sortOrder: 2 },',
        '    { id: "dessert", name: "Desserts", sortOrder: 3 },',
        '  ];',
        '',
        '  let cart: Array<{ itemId: string; quantity: number }> = [];',
        '  const prices: Record<string, number> = {};',
        '  for (const item of menuItems) { prices[item.id] = item.price; }',
        '',
        '  const list = document.createElement("section");',
        '  list.setAttribute("aria-label", "Menu");',
        '',
        '  const status = document.createElement("p");',
        '  status.className = "muted";',
        '  status.textContent = "Loading menu…";',
        '',
        '  const renderList = (): void => {',
        '    list.replaceChildren();',
        '    for (const group of groupByCategory(menuItems, categories)) {',
        '      if (group.items.length === 0) continue;',
        '      const heading = document.createElement("h2");',
        '      heading.textContent = group.category.name;',
        '      list.appendChild(heading);',
        '      for (const item of group.items) {',
        '        const row = document.createElement("div");',
        '        row.className = "row";',
        '        const name = document.createElement("span");',
        '        name.textContent = `${item.name} — $${item.price}`;',
        '        const add = document.createElement("button");',
        '        add.type = "button";',
        '        add.setAttribute("aria-label", `Add ${item.name} to cart`);',
        '        add.textContent = "Add";',
        '        add.addEventListener("click", () => {',
        '          cart = addToCart(cart, item.id);',
        '          status.textContent = `Cart total: $${cartTotal(cart, prices)} — ${cart.length} line(s).`;',
        '        });',
        '        row.append(name, add);',
        '        list.appendChild(row);',
        '      }',
        '    }',
        '    status.textContent = "Menu loaded — add items to build your order.";',
        '  };',
        '',
        '  renderList();',
        '  shell.append(title, list, status);',
        '  root.appendChild(shell);',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/ui/app.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { uiTitle, render } from "./app.js";',
        '',
        'describe("Restaurant UI entry", () => {',
        '  it("exposes a render function and a title", () => {',
        '    expect(typeof render).toBe("function");',
        '    expect(uiTitle).toContain("Restaurant");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui-design.md',
      [
        '# UI Design — Restaurant App',
        'Responsive: menu grid on desktop (lg:grid-cols-4), stacked cards on mobile.',
        'Navigation: bottom tab bar on mobile, top navbar on desktop (Menu, Cart, Orders, Admin).',
        'Loading states: menu skeletons while fetching. Empty state: "No items in this category".',
        'Error states: order failure banner with retry.',
        'Accessibility: aria-labels on cart buttons, focus rings, 4.5:1 contrast.',
        'Dark/light mode: theme toggle; color palette tokens (primary/orange, surface slate).',
        'Admin views: orders dashboard with status management.',
        'Spacing: 4px scale; typography: Inter, 14/16/20/28 scale.',
      ].join('\n'),
      'docs',
    ),
    file(
      'db/schema.sql',
      [
        'CREATE TABLE IF NOT EXISTS categories (id UUID PRIMARY KEY, name TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0);',
        'CREATE TABLE IF NOT EXISTS menu_items (',
        '  id UUID PRIMARY KEY, category_id UUID REFERENCES categories(id),',
        '  name TEXT NOT NULL, price NUMERIC(10,2) NOT NULL, available BOOLEAN NOT NULL DEFAULT true',
        ');',
        'CREATE TABLE IF NOT EXISTS orders (',
        '  id UUID PRIMARY KEY, user_id UUID NOT NULL, status TEXT NOT NULL, total NUMERIC(10,2) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()',
        ');',
        'CREATE TABLE IF NOT EXISTS order_items (',
        '  id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id),',
        '  item_id UUID REFERENCES menu_items(id), quantity INT NOT NULL, unit_price NUMERIC(10,2) NOT NULL',
        ');',
      ].join('\n'),
      'schema',
    ),
  ];
  return applyDefects(files, options);
}

function generateAiBuilder(options: GenerateOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [
    file(
      'package.json',
      JSON.stringify(
        {
          name: options.name,
          version: '0.1.0',
          private: true,
          scripts: { build: 'tsc -p tsconfig.json', test: 'vitest run', lint: 'tsc --noEmit' },
          dependencies: { '@vedmoulya/core': '*', '@vedmoulya/loop-engine': '*' },
          devDependencies: { typescript: '^5.6.0', vitest: '^4.1.10' },
        },
        null,
        2,
      ),
      'config',
    ),
    file(
      'tsconfig.json',
      JSON.stringify(
        { compilerOptions: { strict: true, target: 'ES2022', module: 'ESNext' }, include: ['src'] },
        null,
        2,
      ),
      'config',
    ),
    file(
      'src/index.ts',
      [
        'export { createProject } from "./projects.js";',
        'export { serializeBlueprint } from "./blueprint.js";',
        '',
        'export type { AppProject, ProjectStatus } from "./projects.js";',
        'export type { GeneratedBlueprint } from "./blueprint.js";',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/index.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { createProject, serializeBlueprint } from "./index.js";',
        '',
        'describe("builder entry", () => {',
        '  it("re-exports the builder modules", () => {',
        '    expect(typeof createProject).toBe("function");',
        '    expect(typeof serializeBlueprint).toBe("function");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/projects.ts',
      [
        'export type ProjectStatus = "draft" | "planned" | "building" | "validating" | "ready";',
        '',
        'export interface AppProject { id: string; ownerId: string; goal: string; status: ProjectStatus; }',
        '',
        'export function createProject(ownerId: string, goal: string): AppProject {',
        '  return { id: crypto.randomUUID(), ownerId, goal, status: "draft" };',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/blueprint.ts',
      [
        'export interface GeneratedBlueprint { projectId: string; blueprintJson: string; version: string; }',
        '',
        'export function serializeBlueprint(projectId: string, data: unknown): GeneratedBlueprint {',
        '  return { projectId, blueprintJson: JSON.stringify(data), version: "1.0.0" };',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/projects.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { createProject } from "./projects.js";',
        '',
        'describe("projects", () => {',
        '  it("creates a project from a goal", () => {',
        '    const project = createProject("u1", "Build a restaurant app");',
        '    expect(project.status).toBe("draft");',
        '    expect(project.goal).toContain("restaurant");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/blueprint.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { serializeBlueprint } from "./blueprint.js";',
        '',
        'describe("blueprint", () => {',
        '  it("serializes a blueprint", () => {',
        '    const bp = serializeBlueprint("p1", { name: "Demo" });',
        '    expect(bp.version).toBe("1.0.0");',
        '    expect(bp.blueprintJson).toContain("Demo");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui/app.ts',
      [
        '// Deterministic UI entry — bundled by the gateway preview sandbox (Phase 13).',
        "import { createProject, serializeBlueprint } from '../index.js';",
        '',
        'export const uiTitle = "AI App Builder";',
        '',
        'export function render(root: HTMLElement): void {',
        '  const style = document.createElement("style");',
        '  style.textContent = [',
        '    ":root { color-scheme: light dark; --bg: #ffffff; --fg: #0f172a; --accent: #7c3aed; }",',
        '    "@media (prefers-color-scheme: dark) { :root { --bg: #0f172a; --fg: #e2e8f0; } }",',
        '    "body { margin: 0; font-family: system-ui, Inter, sans-serif; background: var(--bg); color: var(--fg); }",',
        '    ".shell { max-width: 720px; margin: 0 auto; padding: 24px; display: flex; flex-direction: column; gap: 12px; }",',
        '    "@media (max-width: 768px) { .shell { padding: 16px; } }",',
        '    "input { width: 100%; box-sizing: border-box; padding: 8px; border: 1px solid #cbd5e1; border-radius: 8px; font: inherit; }",',
        '    "button { padding: 8px 16px; border: 0; border-radius: 8px; background: var(--accent); color: #fff; font: inherit; cursor: pointer; }",',
        '    ".card { border: 1px solid rgba(127,127,127,0.25); border-radius: 8px; padding: 10px; font-size: 14px; }",',
        '    ".muted { color: #64748b; font-size: 12px; }",',
        '  ].join("\\n");',
        '  root.appendChild(style);',
        '',
        '  const shell = document.createElement("main");',
        '  shell.className = "shell";',
        '',
        '  const title = document.createElement("h1");',
        '  title.textContent = uiTitle;',
        '',
        '  const goalLabel = document.createElement("label");',
        '  goalLabel.setAttribute("aria-label", "Application idea");',
        '  const goal = document.createElement("input");',
        '  goal.placeholder = "Describe the application you want to build…";',
        '  goalLabel.appendChild(goal);',
        '',
        '  const build = document.createElement("button");',
        '  build.type = "button";',
        '  build.textContent = "Generate plan";',
        '',
        '  const status = document.createElement("p");',
        '  status.className = "muted";',
        '  status.textContent = "Empty — describe an idea to begin.";',
        '',
        '  const output = document.createElement("section");',
        '  output.setAttribute("aria-live", "polite");',
        '',
        '  build.addEventListener("click", () => {',
        '    const idea = goal.value.trim();',
        '    if (!idea) {',
        '      status.textContent = "Empty — describe an idea first.";',
        '      output.replaceChildren();',
        '      return;',
        '    }',
        '    status.textContent = "Loading — generating…";',
        '    try {',
        '      const project = createProject("demo-user", idea);',
        '      const blueprint = serializeBlueprint(project.id, { goal: idea });',
        '      const card = document.createElement("div");',
        '      card.className = "card";',
        '      card.textContent = `Project ${project.id} — ${project.status}. Blueprint v${blueprint.version}.`;',
        '      output.replaceChildren(card);',
        '      status.textContent = "Done — plan generated.";',
        '    } catch (err) {',
        '      const fail = document.createElement("div");',
        '      fail.className = "card";',
        '      fail.textContent = err instanceof Error ? err.message : "Generation failed.";',
        '      output.replaceChildren(fail);',
        '      status.textContent = "Error — generation failed.";',
        '    }',
        '  });',
        '',
        '  shell.append(title, goalLabel, build, status, output);',
        '  root.appendChild(shell);',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/ui/app.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { uiTitle, render } from "./app.js";',
        '',
        'describe("Builder UI entry", () => {',
        '  it("exposes a render function and a title", () => {',
        '    expect(typeof render).toBe("function");',
        '    expect(uiTitle).toContain("App Builder");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui-design.md',
      [
        '# UI Design — AI App Builder',
        'Responsive wizard: Describe → Review → Approve → Generate → Validate.',
        'Navigation: stepper with back/next; progress indicator.',
        'Loading states: spinner while the blueprint generates. Empty state: no projects yet.',
        'Error states: generation failure card with retry.',
        'Accessibility: aria-current on stepper, focus management between steps.',
        'Dark/light mode supported. Design tokens: spacing 4px scale, Inter typography.',
      ].join('\n'),
      'docs',
    ),
    file(
      'db/schema.sql',
      [
        'CREATE TABLE IF NOT EXISTS projects (',
        '  id UUID PRIMARY KEY, owner_id UUID NOT NULL, goal TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()',
        ');',
        'CREATE TABLE IF NOT EXISTS generated_blueprints (',
        '  id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id),',
        '  blueprint_json JSONB NOT NULL, version TEXT NOT NULL',
        ');',
      ].join('\n'),
      'schema',
    ),
  ];
  return applyDefects(files, options);
}

function generateGeneric(options: GenerateOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [
    file(
      'package.json',
      JSON.stringify(
        {
          name: options.name,
          version: '0.1.0',
          private: true,
          scripts: { build: 'tsc -p tsconfig.json', test: 'vitest run', lint: 'tsc --noEmit' },
          dependencies: { '@vedmoulya/core': '*' },
          devDependencies: { typescript: '^5.6.0', vitest: '^4.1.10' },
        },
        null,
        2,
      ),
      'config',
    ),
    file(
      'tsconfig.json',
      JSON.stringify(
        { compilerOptions: { strict: true, target: 'ES2022', module: 'ESNext' }, include: ['src'] },
        null,
        2,
      ),
      'config',
    ),
    file(
      'src/index.ts',
      [
        'export interface Item { id: string; name: string; }',
        'export function createItem(name: string): Item { return { id: crypto.randomUUID(), name }; }',
      ].join('\n'),
      'source',
    ),
    file(
      'src/index.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { createItem } from "./index.js";',
        'describe("generic app", () => {',
        '  it("creates an item", () => { expect(createItem("x").name).toBe("x"); });',
        '});',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui/app.ts',
      [
        '// Deterministic UI entry — bundled by the gateway preview sandbox (Phase 13).',
        "import { createItem } from '../index.js';",
        '',
        'export const uiTitle = "Item Manager";',
        '',
        'export function render(root: HTMLElement): void {',
        '  const style = document.createElement("style");',
        '  style.textContent = [',
        '    ":root { color-scheme: light dark; --bg: #ffffff; --fg: #0f172a; }",',
        '    "@media (prefers-color-scheme: dark) { :root { --bg: #0f172a; --fg: #e2e8f0; } }",',
        '    "body { margin: 0; font-family: system-ui, Inter, sans-serif; background: var(--bg); color: var(--fg); }",',
        '    ".shell { max-width: 720px; margin: 0 auto; padding: 24px; display: flex; flex-direction: column; gap: 12px; }",',
        '    "@media (max-width: 768px) { .shell { padding: 16px; } }",',
        '    "input { padding: 8px; border: 1px solid #cbd5e1; border-radius: 8px; font: inherit; }",',
        '    "button { padding: 8px 16px; border: 0; border-radius: 8px; background: #2b5fd9; color: #fff; font: inherit; cursor: pointer; }",',
        '    ".row { border-bottom: 1px solid rgba(127,127,127,0.2); padding: 6px 0; font-size: 14px; }",',
        '    ".muted { color: #64748b; font-size: 12px; }",',
        '  ].join("\\n");',
        '  root.appendChild(style);',
        '',
        '  const shell = document.createElement("main");',
        '  shell.className = "shell";',
        '',
        '  const title = document.createElement("h1");',
        '  title.textContent = uiTitle;',
        '',
        '  const label = document.createElement("label");',
        '  label.setAttribute("aria-label", "Item name");',
        '  const name = document.createElement("input");',
        '  name.placeholder = "New item name";',
        '  label.appendChild(name);',
        '',
        '  const add = document.createElement("button");',
        '  add.type = "button";',
        '  add.textContent = "Add item";',
        '',
        '  const status = document.createElement("p");',
        '  status.className = "muted";',
        '  status.textContent = "Empty — no items yet.";',
        '',
        '  const list = document.createElement("section");',
        '  list.setAttribute("aria-label", "Items");',
        '',
        '  add.addEventListener("click", () => {',
        '    const value = name.value.trim();',
        '    if (!value) {',
        '      status.textContent = "Empty — enter a name first.";',
        '      return;',
        '    }',
        '    const item = createItem(value);',
        '    const row = document.createElement("div");',
        '    row.className = "row";',
        '    row.textContent = `${item.name} (${item.id})`;',
        '    list.appendChild(row);',
        '    name.value = "";',
        '    status.textContent = `Added ${item.name}.`;',
        '  });',
        '',
        '  shell.append(title, label, add, status, list);',
        '  root.appendChild(shell);',
        '}',
        '',
      ].join('\n'),
      'source',
    ),
    file(
      'src/ui/app.test.ts',
      [
        'import { describe, expect, it } from "vitest";',
        'import { uiTitle, render } from "./app.js";',
        '',
        'describe("Generic UI entry", () => {',
        '  it("exposes a render function and a title", () => {',
        '    expect(typeof render).toBe("function");',
        '    expect(uiTitle).toContain("Item");',
        '  });',
        '});',
        '',
      ].join('\n'),
      'test',
    ),
    file(
      'src/ui-design.md',
      [
        '# UI Design',
        'Responsive layout, clear navigation, loading/empty/error states, accessible, dark mode.',
      ].join('\n'),
      'docs',
    ),
    file(
      'db/schema.sql',
      'CREATE TABLE IF NOT EXISTS items (id UUID PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());\n',
      'schema',
    ),
  ];
  return applyDefects(files, options);
}

function applyDefects(files: GeneratedFile[], options: GenerateOptions): GeneratedFile[] {
  let result = files;
  if (options.injectDefects) {
    // Drop one test file so the auto-fix path is exercised.
    result = result.filter((f) => !f.path.includes('.test.'));
  }
  if (options.injectSecret) {
    result = result.map((f) =>
      f.path === 'src/index.ts'
        ? {
            ...f,
            content: `${f.content}\n// TODO: remove\nconst SECRET_TOKEN = "sk-live-abcdef0123456789abcdef";\n`,
          }
        : f,
    );
  }
  return result;
}

function file(path: string, content: string, kind: BlueprintFile['kind']): GeneratedFile {
  return { path, content, kind };
}
