// ──────────────────────────────────────────────────────────────────
// VedMoulya — Content Agency Application Service tests
// EPIC-003 / SPRINT AC-001 — AI Content Agency Foundation
// ──────────────────────────────────────────────────────────────────

import { describe, it, expect, vi, beforeEach } from 'vitest';

import { ContentAgencyApplicationService } from '../ContentAgencyApplicationService.js';
import { InMemoryContentAgencyRepository } from '../InMemoryContentAgencyRepository.js';
import { ContentAgencyAIService } from '../ContentAgencyAIService.js';
import type { AIOrchestrationService } from '../../ai/AIOrchestrationService.js';

const aiResponse = {
  content: '# Draft content\n\nOn-brand copy generated by the pipeline.',
  provider: 'mock',
  model: 'mock-standard',
  qualityScore: 8,
  traceId: 'trace_1',
  tokenUsage: { input: 120, output: 340, total: 460 },
  cost: 0.0042,
  latency: 42,
};

function makeService(overrides: { orchestrate?: unknown } = {}) {
  const repo = new InMemoryContentAgencyRepository();
  const aiMock = {
    orchestrate:
      overrides.orchestrate instanceof Error
        ? vi.fn().mockRejectedValue(overrides.orchestrate)
        : vi.fn().mockResolvedValue(overrides.orchestrate ?? aiResponse),
  } as unknown as AIOrchestrationService;
  const ai = new ContentAgencyAIService(aiMock);
  const svc = new ContentAgencyApplicationService(repo, ai);
  return { svc, repo, aiMock };
}

const USER = 'user-1';

const clientInput = {
  company: 'Acme Inc',
  industry: 'SaaS',
  brandVoice: 'bold and helpful',
  targetAudience: 'CTOs of mid-size companies',
  products: ['Acme Analytics', 'Acme Sync'],
  services: ['Implementation', 'Support'],
  goals: ['Increase demo bookings', 'Shorten sales cycle'],
  website: 'https://acme.example',
  socialLinks: { linkedin: 'https://linkedin.com/company/acme' },
};

describe('ContentAgencyApplicationService — clients', () => {
  it('creates a client with defaults and timestamps', async () => {
    const { svc } = makeService();
    const res = await svc.createClient(USER, clientInput);
    expect(res.success).toBe(true);
    expect(res.data?.company).toBe('Acme Inc');
    expect(res.data?.industry).toBe('SaaS');
    expect(res.data?.products).toEqual(['Acme Analytics', 'Acme Sync']);
    expect(res.data?.createdAt).toBeDefined();
    expect(res.data?.userId).toBe(USER);
  });

  it('rejects empty company name', async () => {
    const { svc } = makeService();
    const res = await svc.createClient(USER, { company: '  ' });
    expect(res.success).toBe(false);
    expect(res.error).toMatch(/company/i);
  });

  it('lists, updates and deletes clients scoped to the user', async () => {
    const { svc } = makeService();
    const created = await svc.createClient(USER, clientInput);
    const id = created.data!.id;

    const listed = await svc.listClients(USER);
    expect(listed.data).toHaveLength(1);

    const otherUser = await svc.getClient('other-user', id);
    expect(otherUser.success).toBe(false);

    const updated = await svc.updateClient(USER, id, { industry: 'Fintech' });
    expect(updated.data?.industry).toBe('Fintech');

    const deleted = await svc.deleteClient(USER, id);
    expect(deleted.success).toBe(true);
    expect((await svc.listClients(USER)).data).toHaveLength(0);
  });
});

describe('ContentAgencyApplicationService — brands & projects', () => {
  it('upserts a brand and updates in place', async () => {
    const { svc } = makeService();
    const brand = await svc.upsertBrand(USER, {
      name: 'Acme Voice',
      tone: 'confident',
      writingStyle: 'short sentences',
      vocabulary: ['delightful', 'simple'],
      doRules: ['Use active voice'],
      dontRules: ['No jargon'],
      keywords: ['analytics', 'sync'],
      colorPalette: ['#0F172A', '#3B82F6'],
      mission: 'Make data simple',
    });
    expect(brand.success).toBe(true);
    expect(brand.data?.doRules).toEqual(['Use active voice']);

    const updated = await svc.upsertBrand(USER, { id: brand.data!.id, name: 'Acme Voice 2' });
    expect(updated.data?.name).toBe('Acme Voice 2');
    expect(updated.data?.tone).toBe('confident'); // untouched field preserved
  });

  it('creates projects only for existing clients', async () => {
    const { svc } = makeService();
    const noClient = await svc.createProject(USER, { clientId: 'nope', name: 'X' });
    expect(noClient.success).toBe(false);

    const client = await svc.createClient(USER, clientInput);
    const project = await svc.createProject(USER, {
      clientId: client.data!.id,
      name: 'Q3 Content Sprint',
    });
    expect(project.success).toBe(true);
    expect(project.data?.status).toBe('active');
  });
});

describe('ContentAgencyApplicationService — generation pipeline', () => {
  it('generates content through the AI pipeline and saves a traceable asset', async () => {
    const { svc, repo } = makeService();
    const client = await svc.createClient(USER, clientInput);
    const brand = await svc.upsertBrand(USER, { name: 'Acme Voice', clientId: client.data!.id });

    const res = await svc.generateContent(USER, {
      clientId: client.data!.id,
      brandId: brand.data!.id,
      contentType: 'blog',
      title: 'Why data teams love realtime sync',
      brief: 'A thought-leadership blog on realtime data sync.',
    });

    expect(res.success).toBe(true);
    expect(res.data?.status).toBe('draft');
    expect(res.data?.versions).toHaveLength(1);
    expect(res.data?.versions[0].generatedBy).toBe('ai');
    expect(res.data?.aiMetadata).toBeDefined();
    expect(res.data?.aiMetadata?.provider).toBe('mock');
    expect(res.data?.aiMetadata?.traceId).toBe('trace_1');
    expect(res.data?.aiMetadata?.prompt.sections).toContain('draft');
    expect(res.data?.aiMetadata?.passes.length).toBeGreaterThanOrEqual(2); // brand + grammar
    expect(res.data?.aiMetadata?.qualityScore).toBeGreaterThan(0);

    // Persisted: listContent returns it.
    const listed = await repo.listContent(USER);
    expect(listed).toHaveLength(1);
  });

  it('surfaces a clear error when the orchestrator fails', async () => {
    const { svc } = makeService({ orchestrate: new Error('No provider available') });
    const client = await svc.createClient(USER, clientInput);
    const res = await svc.generateContent(USER, {
      clientId: client.data!.id,
      contentType: 'linkedin',
      title: 'Post',
      brief: 'Post brief',
    });
    expect(res.success).toBe(false);
    expect(res.error).toMatch(/provider/i);
  });

  it('creates manual drafts (human-authored)', async () => {
    const { svc } = makeService();
    const client = await svc.createClient(USER, clientInput);
    const res = await svc.createDraft(USER, {
      clientId: client.data!.id,
      contentType: 'email',
      title: 'Welcome email',
      brief: 'Onboarding email',
      content: 'Hello and welcome!',
    });
    expect(res.success).toBe(true);
    expect(res.data?.versions[0].generatedBy).toBe('human');
    expect(res.data?.aiMetadata).toBeNull();
  });
});

describe('ContentAgencyApplicationService — workflow & approval', () => {
  async function seed(overrides = {}) {
    const m = makeService(overrides);
    const client = await m.svc.createClient(USER, clientInput);
    const gen = await m.svc.generateContent(USER, {
      clientId: client.data!.id,
      contentType: 'blog',
      title: 'The future of work',
      brief: 'Trends shaping work.',
    });
    return { ...m, client: client.data!, content: gen.data! };
  }

  it('transitions status through the workflow', async () => {
    const { svc, content } = await seed();
    const review = await svc.transitionStatus(USER, content.id, 'review');
    expect(review.data?.status).toBe('review');
    expect(review.data?.workflowStage).toBe('review');
    const approved = await svc.transitionStatus(USER, content.id, 'approved');
    expect(approved.data?.status).toBe('approved');
    expect(approved.data?.workflowStage).toBe('approval');
  });

  it('schedules and publishes content', async () => {
    const { svc, content } = await seed();
    const scheduled = await svc.scheduleContent(USER, content.id, '2026-09-01T09:00:00Z');
    expect(scheduled.data?.status).toBe('scheduled');
    const published = await svc.publishContent(
      USER,
      content.id,
      'https://acme.example/blog/future',
    );
    expect(published.data?.status).toBe('published');
    expect(published.data?.publishedUrl).toBe('https://acme.example/blog/future');
    const again = await svc.transitionStatus(USER, content.id, 'review');
    expect(again.success).toBe(false); // published content is terminal
  });

  it('review accept → approved, reject → review, comment keeps history', async () => {
    const { svc, content } = await seed();
    const accepted = await svc.addReview(USER, content.id, {
      stage: 'brand_alignment',
      reviewer: 'Jane',
      comment: 'Looks great',
      decision: 'accepted',
      score: 9,
    });
    expect(accepted.data?.status).toBe('approved');
    expect(accepted.data?.reviews).toHaveLength(1);
    expect(accepted.data?.reviews[0].score).toBe(9);

    const rejected = await svc.addReview(USER, content.id, {
      stage: 'grammar',
      reviewer: 'Bob',
      comment: 'Fix typos',
      decision: 'rejected',
    });
    expect(rejected.data?.status).toBe('review');
    expect(rejected.data?.reviews).toHaveLength(2);
  });

  it('regenerates with feedback, appending a new version', async () => {
    const { svc, content } = await seed();
    const regen = await svc.regenerateContent(USER, content.id, {
      feedback: 'Make it punchier and add a CTA',
    });
    expect(regen.success).toBe(true);
    expect(regen.data?.versions).toHaveLength(2);
    expect(regen.data?.versions[1].feedback).toBe('Make it punchier and add a CTA');
    expect(regen.data?.status).toBe('review');
    expect(regen.data?.aiMetadata?.prompt.sections).toContain('regenerate');
  });

  it('refuses to regenerate human drafts', async () => {
    const { svc } = makeService();
    const client = await svc.createClient(USER, clientInput);
    const draft = await svc.createDraft(USER, {
      clientId: client.data!.id,
      contentType: 'email',
      title: 'Manual',
      brief: 'b',
      content: 'Hello',
    });
    const res = await svc.regenerateContent(USER, draft.data!.id, { feedback: 'x' });
    expect(res.success).toBe(false);
  });
});

describe('ContentAgencyApplicationService — calendar, invoices, analytics, delivery', () => {
  async function seedTwo() {
    const { svc } = makeService();
    const client = await svc.createClient(USER, clientInput);
    const a = await svc.generateContent(USER, {
      clientId: client.data!.id,
      contentType: 'blog',
      title: 'Scheduled post A',
      brief: 'b',
    });
    const b = await svc.generateContent(USER, {
      clientId: client.data!.id,
      contentType: 'linkedin',
      title: 'Scheduled post B',
      brief: 'b',
    });
    await svc.scheduleContent(USER, a.data!.id, '2026-09-10T09:00:00Z');
    await svc.scheduleContent(USER, b.data!.id, '2026-09-15T09:00:00Z');
    return { svc, client: client.data! };
  }

  it('returns calendar entries for month/week/day ranges', async () => {
    const { svc } = await seedTwo();
    const month = await svc.getCalendar(USER, 'month', '2026-09-01');
    expect(month.data).toHaveLength(2);
    expect(month.data![0].clientName).toBe('Acme Inc');
    const day = await svc.getCalendar(USER, 'day', '2026-09-10');
    expect(day.data).toHaveLength(1);
    const other = await svc.getCalendar(USER, 'day', '2026-10-01');
    expect(other.data).toHaveLength(0);
  });

  it('manages invoices and revenue analytics', async () => {
    const { svc } = await seedTwo();
    const inv = await svc.createInvoice(USER, {
      clientId: 'whatever',
      amount: 500,
    });
    expect(inv.success).toBe(false);

    const client = await svc.createClient(USER, clientInput);
    const invoice = await svc.createInvoice(USER, {
      clientId: client.data!.id,
      amount: 2500,
      description: 'Monthly retainer',
      currency: 'USD',
    });
    expect(invoice.success).toBe(true);

    const analyticsDraft = await svc.getAnalytics(USER);
    expect(analyticsDraft.data?.revenue).toBe(0); // draft invoices excluded

    await svc.updateInvoiceStatus(USER, invoice.data!.id, 'paid');
    const analytics = await svc.getAnalytics(USER);
    expect(analytics.data?.revenue).toBe(2500);
    expect(analytics.data?.clients).toBe(2);
    expect(analytics.data?.contentCreated).toBe(2);
    expect(analytics.data?.aiUsage.generations).toBe(2);
    expect(analytics.data?.byContentType.blog).toBe(1);
    // Both seeded items were scheduled → not drafts.
    expect(analytics.data?.byStatus.scheduled).toBe(2);
  });

  it('builds a dashboard view with upcoming and recent content', async () => {
    const { svc } = await seedTwo();
    const dash = await svc.getDashboard(USER);
    expect(dash.success).toBe(true);
    expect(dash.data?.upcomingContent.length).toBe(2);
    expect(dash.data?.recentContent.length).toBe(2);
    expect(dash.data?.analytics.contentCreated).toBe(2);
  });

  it('exports content as markdown and html', async () => {
    const { svc } = await seedTwo();
    const item = (await svc.listContent(USER)).data![0];
    const md = await svc.exportContent(USER, item.id, 'markdown');
    expect(md.success).toBe(true);
    expect(md.data?.filename).toMatch(/\.md$/);
    expect(md.data?.data).toContain('# ');

    const html = await svc.exportContent(USER, item.id, 'html');
    expect(html.data?.data).toContain('<h1>');
    expect(html.data?.data).toContain('<p>');

    const pdf = await svc.exportContent(USER, item.id, 'pdf');
    expect(pdf.data?.supported).toBe(false); // roadmap item
  });

  it('rejects unknown content for export', async () => {
    const { svc } = makeService();
    const res = await svc.exportContent(USER, 'missing', 'markdown');
    expect(res.success).toBe(false);
  });
});
